# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exchange(object):
    def setupUi(self, Exchange):
        Exchange.setObjectName("Exchange")
        Exchange.resize(432, 545)
        Exchange.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("汇率.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Exchange.setWindowIcon(icon)
        self.label_1 = QtWidgets.QLabel(Exchange)
        self.label_1.setGeometry(QtCore.QRect(50, 20, 231, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.cur_name = QtWidgets.QComboBox(Exchange)
        self.cur_name.setGeometry(QtCore.QRect(40, 130, 151, 31))
        self.cur_name.setObjectName("cur_name")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_name.addItem("")
        self.cur_class = QtWidgets.QComboBox(Exchange)
        self.cur_class.setGeometry(QtCore.QRect(220, 130, 161, 31))
        self.cur_class.setObjectName("cur_class")
        self.cur_class.addItem("")
        self.cur_class.addItem("")
        self.cur_class.addItem("")
        self.cur_class.addItem("")
        self.cur_class.addItem("")
        self.cur_inquiry = QtWidgets.QPushButton(Exchange)
        self.cur_inquiry.setGeometry(QtCore.QRect(40, 180, 341, 31))
        self.cur_inquiry.setObjectName("cur_inquiry")
        self.display_bar1 = QtWidgets.QLineEdit(Exchange)
        self.display_bar1.setGeometry(QtCore.QRect(40, 80, 341, 31))
        self.display_bar1.setObjectName("display_bar1")
        self.label_3 = QtWidgets.QLabel(Exchange)
        self.label_3.setGeometry(QtCore.QRect(90, 220, 241, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.display_bar2 = QtWidgets.QLineEdit(Exchange)
        self.display_bar2.setGeometry(QtCore.QRect(220, 270, 161, 31))
        self.display_bar2.setObjectName("display_bar2")
        self.get_cur_name = QtWidgets.QComboBox(Exchange)
        self.get_cur_name.setGeometry(QtCore.QRect(40, 270, 151, 31))
        self.get_cur_name.setObjectName("get_cur_name")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.get_cur_name.addItem("")
        self.label_2 = QtWidgets.QLabel(Exchange)
        self.label_2.setGeometry(QtCore.QRect(280, 50, 151, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.icon = QtWidgets.QLabel(Exchange)
        self.icon.setGeometry(QtCore.QRect(180, 390, 71, 71))
        self.icon.setStyleSheet("image: url(:/新前缀/汇率转换.png);")
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.display_bar3 = QtWidgets.QLineEdit(Exchange)
        self.display_bar3.setGeometry(QtCore.QRect(40, 370, 341, 31))
        self.display_bar3.setObjectName("display_bar3")
        self.from_cur = QtWidgets.QComboBox(Exchange)
        self.from_cur.setGeometry(QtCore.QRect(40, 420, 141, 21))
        self.from_cur.setObjectName("from_cur")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.from_cur.addItem("")
        self.to_cur = QtWidgets.QComboBox(Exchange)
        self.to_cur.setGeometry(QtCore.QRect(240, 420, 141, 21))
        self.to_cur.setObjectName("to_cur")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.to_cur.addItem("")
        self.label_4 = QtWidgets.QLabel(Exchange)
        self.label_4.setGeometry(QtCore.QRect(80, 320, 291, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.exchange_inquiry = QtWidgets.QPushButton(Exchange)
        self.exchange_inquiry.setGeometry(QtCore.QRect(40, 460, 341, 31))
        self.exchange_inquiry.setObjectName("exchange_inquiry")
        self.timelabel = QtWidgets.QLabel(Exchange)
        self.timelabel.setGeometry(QtCore.QRect(160, 510, 251, 21))
        self.timelabel.setObjectName("timelabel")
        self.label = QtWidgets.QLabel(Exchange)
        self.label.setGeometry(QtCore.QRect(40, 510, 111, 20))
        self.label.setObjectName("label")

        self.retranslateUi(Exchange)
        QtCore.QMetaObject.connectSlotsByName(Exchange)

    def retranslateUi(self, Exchange):
        _translate = QtCore.QCoreApplication.translate
        Exchange.setWindowTitle(_translate("Exchange", "汇率查询"))
        self.label_1.setText(_translate("Exchange", "当日实时汇率查询"))
        self.cur_name.setItemText(0, _translate("Exchange", "货币名称"))
        self.cur_name.setItemText(1, _translate("Exchange", "美元"))
        self.cur_name.setItemText(2, _translate("Exchange", "韩元"))
        self.cur_name.setItemText(3, _translate("Exchange", "日元"))
        self.cur_name.setItemText(4, _translate("Exchange", "港币"))
        self.cur_name.setItemText(5, _translate("Exchange", "英镑"))
        self.cur_name.setItemText(6, _translate("Exchange", "欧元"))
        self.cur_name.setItemText(7, _translate("Exchange", "加拿大元"))
        self.cur_name.setItemText(8, _translate("Exchange", "澳大利亚元"))
        self.cur_class.setItemText(0, _translate("Exchange", "查询类别"))
        self.cur_class.setItemText(1, _translate("Exchange", "现汇买入价"))
        self.cur_class.setItemText(2, _translate("Exchange", "现钞买入价"))
        self.cur_class.setItemText(3, _translate("Exchange", "现钞卖出价"))
        self.cur_class.setItemText(4, _translate("Exchange", "中行折算价"))
        self.cur_inquiry.setText(_translate("Exchange", "查      询"))
        self.label_3.setText(_translate("Exchange", "世界流通货币缩写查询"))
        self.get_cur_name.setItemText(0, _translate("Exchange", "货币名称"))
        self.get_cur_name.setItemText(1, _translate("Exchange", "人民币"))
        self.get_cur_name.setItemText(2, _translate("Exchange", "美元"))
        self.get_cur_name.setItemText(3, _translate("Exchange", "日元"))
        self.get_cur_name.setItemText(4, _translate("Exchange", "欧元"))
        self.get_cur_name.setItemText(5, _translate("Exchange", "英镑"))
        self.get_cur_name.setItemText(6, _translate("Exchange", "韩元"))
        self.get_cur_name.setItemText(7, _translate("Exchange", "港币"))
        self.get_cur_name.setItemText(8, _translate("Exchange", "澳大利亚元"))
        self.get_cur_name.setItemText(9, _translate("Exchange", "加拿大元"))
        self.get_cur_name.setItemText(10, _translate("Exchange", "阿尔及利亚第纳尔"))
        self.get_cur_name.setItemText(11, _translate("Exchange", "阿根廷比索"))
        self.get_cur_name.setItemText(12, _translate("Exchange", "爱尔兰镑"))
        self.get_cur_name.setItemText(13, _translate("Exchange", "埃及镑"))
        self.get_cur_name.setItemText(14, _translate("Exchange", "阿联酋迪拉姆"))
        self.get_cur_name.setItemText(15, _translate("Exchange", "阿曼里亚尔"))
        self.get_cur_name.setItemText(16, _translate("Exchange", "奥地利先令"))
        self.get_cur_name.setItemText(17, _translate("Exchange", "澳门元"))
        self.get_cur_name.setItemText(18, _translate("Exchange", "百慕大元"))
        self.get_cur_name.setItemText(19, _translate("Exchange", "巴基斯坦卢比"))
        self.get_cur_name.setItemText(20, _translate("Exchange", "巴拉圭瓜拉尼"))
        self.get_cur_name.setItemText(21, _translate("Exchange", "巴林第纳尔"))
        self.get_cur_name.setItemText(22, _translate("Exchange", "巴拿马巴尔博亚"))
        self.get_cur_name.setItemText(23, _translate("Exchange", "保加利亚列弗"))
        self.get_cur_name.setItemText(24, _translate("Exchange", "巴西雷亚尔"))
        self.get_cur_name.setItemText(25, _translate("Exchange", "比利时法郎"))
        self.get_cur_name.setItemText(26, _translate("Exchange", "冰岛克朗"))
        self.get_cur_name.setItemText(27, _translate("Exchange", "博茨瓦纳普拉"))
        self.get_cur_name.setItemText(28, _translate("Exchange", "波兰兹罗提"))
        self.get_cur_name.setItemText(29, _translate("Exchange", "玻利维亚诺"))
        self.get_cur_name.setItemText(30, _translate("Exchange", "丹麦克朗"))
        self.get_cur_name.setItemText(31, _translate("Exchange", "德国马克"))
        self.get_cur_name.setItemText(32, _translate("Exchange", "法国法郎"))
        self.get_cur_name.setItemText(33, _translate("Exchange", "菲律宾比索"))
        self.get_cur_name.setItemText(34, _translate("Exchange", "芬兰马克"))
        self.get_cur_name.setItemText(35, _translate("Exchange", "哥伦比亚比索"))
        self.get_cur_name.setItemText(36, _translate("Exchange", "古巴比索"))
        self.get_cur_name.setItemText(37, _translate("Exchange", "哈萨克坚戈"))
        self.get_cur_name.setItemText(38, _translate("Exchange", "荷兰盾"))
        self.get_cur_name.setItemText(39, _translate("Exchange", "加纳塞地"))
        self.get_cur_name.setItemText(40, _translate("Exchange", "捷克克朗"))
        self.get_cur_name.setItemText(41, _translate("Exchange", "津巴布韦元"))
        self.get_cur_name.setItemText(42, _translate("Exchange", "卡塔尔里亚尔"))
        self.get_cur_name.setItemText(43, _translate("Exchange", "克罗地亚库纳"))
        self.get_cur_name.setItemText(44, _translate("Exchange", "肯尼亚先令"))
        self.get_cur_name.setItemText(45, _translate("Exchange", "科威特第纳尔"))
        self.get_cur_name.setItemText(46, _translate("Exchange", "老挝基普"))
        self.get_cur_name.setItemText(47, _translate("Exchange", "拉脱维亚拉图"))
        self.get_cur_name.setItemText(48, _translate("Exchange", "黎巴嫩镑"))
        self.get_cur_name.setItemText(49, _translate("Exchange", "林吉特"))
        self.get_cur_name.setItemText(50, _translate("Exchange", "立陶宛立特"))
        self.get_cur_name.setItemText(51, _translate("Exchange", "卢布"))
        self.get_cur_name.setItemText(52, _translate("Exchange", "罗马尼亚新列伊"))
        self.get_cur_name.setItemText(53, _translate("Exchange", "毛里求斯卢比"))
        self.get_cur_name.setItemText(54, _translate("Exchange", "蒙古图格里特"))
        self.get_cur_name.setItemText(55, _translate("Exchange", "孟加拉塔卡"))
        self.get_cur_name.setItemText(56, _translate("Exchange", "缅甸缅元"))
        self.get_cur_name.setItemText(57, _translate("Exchange", "秘鲁新索尔"))
        self.get_cur_name.setItemText(58, _translate("Exchange", "摩洛哥迪拉姆"))
        self.get_cur_name.setItemText(59, _translate("Exchange", "墨西哥元"))
        self.get_cur_name.setItemText(60, _translate("Exchange", "南非兰特"))
        self.get_cur_name.setItemText(61, _translate("Exchange", "挪威克朗"))
        self.get_cur_name.setItemText(62, _translate("Exchange", "葡萄牙埃斯库多"))
        self.get_cur_name.setItemText(63, _translate("Exchange", "瑞典克朗"))
        self.get_cur_name.setItemText(64, _translate("Exchange", "瑞士法郎"))
        self.get_cur_name.setItemText(65, _translate("Exchange", "沙特里亚尔"))
        self.get_cur_name.setItemText(66, _translate("Exchange", "斯里兰卡卢比"))
        self.get_cur_name.setItemText(67, _translate("Exchange", "索马里先令"))
        self.get_cur_name.setItemText(68, _translate("Exchange", "泰铢"))
        self.get_cur_name.setItemText(69, _translate("Exchange", "坦桑尼亚先令"))
        self.get_cur_name.setItemText(70, _translate("Exchange", "新土耳其里拉"))
        self.get_cur_name.setItemText(71, _translate("Exchange", "突尼斯第纳尔"))
        self.get_cur_name.setItemText(72, _translate("Exchange", "危地马拉格查尔"))
        self.get_cur_name.setItemText(73, _translate("Exchange", "委内瑞拉玻利瓦尔"))
        self.get_cur_name.setItemText(74, _translate("Exchange", "乌拉圭新比索"))
        self.get_cur_name.setItemText(75, _translate("Exchange", "西班牙比塞塔"))
        self.get_cur_name.setItemText(76, _translate("Exchange", "希腊德拉克马"))
        self.get_cur_name.setItemText(77, _translate("Exchange", "新加坡元"))
        self.get_cur_name.setItemText(78, _translate("Exchange", "新台币"))
        self.get_cur_name.setItemText(79, _translate("Exchange", "新西兰元"))
        self.get_cur_name.setItemText(80, _translate("Exchange", "匈牙利福林"))
        self.get_cur_name.setItemText(81, _translate("Exchange", "牙买加元"))
        self.get_cur_name.setItemText(82, _translate("Exchange", "义大利里拉"))
        self.get_cur_name.setItemText(83, _translate("Exchange", "印度卢比"))
        self.get_cur_name.setItemText(84, _translate("Exchange", "印尼盾"))
        self.get_cur_name.setItemText(85, _translate("Exchange", "以色列谢克尔"))
        self.get_cur_name.setItemText(86, _translate("Exchange", "约旦第纳尔"))
        self.get_cur_name.setItemText(87, _translate("Exchange", "越南盾"))
        self.get_cur_name.setItemText(88, _translate("Exchange", "智利比索"))
        self.get_cur_name.setItemText(89, _translate("Exchange", "白俄罗斯卢布"))
        self.label_2.setText(_translate("Exchange", "（交易单位：100）"))
        self.from_cur.setItemText(0, _translate("Exchange", "货币名称"))
        self.from_cur.setItemText(1, _translate("Exchange", "人民币"))
        self.from_cur.setItemText(2, _translate("Exchange", "美元"))
        self.from_cur.setItemText(3, _translate("Exchange", "日元"))
        self.from_cur.setItemText(4, _translate("Exchange", "欧元"))
        self.from_cur.setItemText(5, _translate("Exchange", "英镑"))
        self.from_cur.setItemText(6, _translate("Exchange", "韩元"))
        self.from_cur.setItemText(7, _translate("Exchange", "港币"))
        self.from_cur.setItemText(8, _translate("Exchange", "澳大利亚元"))
        self.from_cur.setItemText(9, _translate("Exchange", "加拿大元"))
        self.from_cur.setItemText(10, _translate("Exchange", "阿尔及利亚第纳尔"))
        self.from_cur.setItemText(11, _translate("Exchange", "阿根廷比索"))
        self.from_cur.setItemText(12, _translate("Exchange", "爱尔兰镑"))
        self.from_cur.setItemText(13, _translate("Exchange", "埃及镑"))
        self.from_cur.setItemText(14, _translate("Exchange", "阿联酋迪拉姆"))
        self.from_cur.setItemText(15, _translate("Exchange", "阿曼里亚尔"))
        self.from_cur.setItemText(16, _translate("Exchange", "奥地利先令"))
        self.from_cur.setItemText(17, _translate("Exchange", "澳门元"))
        self.from_cur.setItemText(18, _translate("Exchange", "百慕大元"))
        self.from_cur.setItemText(19, _translate("Exchange", "巴基斯坦卢比"))
        self.from_cur.setItemText(20, _translate("Exchange", "巴拉圭瓜拉尼"))
        self.from_cur.setItemText(21, _translate("Exchange", "巴林第纳尔"))
        self.from_cur.setItemText(22, _translate("Exchange", "巴拿马巴尔博亚"))
        self.from_cur.setItemText(23, _translate("Exchange", "保加利亚列弗"))
        self.from_cur.setItemText(24, _translate("Exchange", "巴西雷亚尔"))
        self.from_cur.setItemText(25, _translate("Exchange", "比利时法郎"))
        self.from_cur.setItemText(26, _translate("Exchange", "冰岛克朗"))
        self.from_cur.setItemText(27, _translate("Exchange", "博茨瓦纳普拉"))
        self.from_cur.setItemText(28, _translate("Exchange", "波兰兹罗提"))
        self.from_cur.setItemText(29, _translate("Exchange", "玻利维亚诺"))
        self.from_cur.setItemText(30, _translate("Exchange", "丹麦克朗"))
        self.from_cur.setItemText(31, _translate("Exchange", "德国马克"))
        self.from_cur.setItemText(32, _translate("Exchange", "法国法郎"))
        self.from_cur.setItemText(33, _translate("Exchange", "菲律宾比索"))
        self.from_cur.setItemText(34, _translate("Exchange", "芬兰马克"))
        self.from_cur.setItemText(35, _translate("Exchange", "哥伦比亚比索"))
        self.from_cur.setItemText(36, _translate("Exchange", "古巴比索"))
        self.from_cur.setItemText(37, _translate("Exchange", "哈萨克坚戈"))
        self.from_cur.setItemText(38, _translate("Exchange", "荷兰盾"))
        self.from_cur.setItemText(39, _translate("Exchange", "加纳塞地"))
        self.from_cur.setItemText(40, _translate("Exchange", "捷克克朗"))
        self.from_cur.setItemText(41, _translate("Exchange", "津巴布韦元"))
        self.from_cur.setItemText(42, _translate("Exchange", "卡塔尔里亚尔"))
        self.from_cur.setItemText(43, _translate("Exchange", "克罗地亚库纳"))
        self.from_cur.setItemText(44, _translate("Exchange", "肯尼亚先令"))
        self.from_cur.setItemText(45, _translate("Exchange", "科威特第纳尔"))
        self.from_cur.setItemText(46, _translate("Exchange", "老挝基普"))
        self.from_cur.setItemText(47, _translate("Exchange", "拉脱维亚拉图"))
        self.from_cur.setItemText(48, _translate("Exchange", "黎巴嫩镑"))
        self.from_cur.setItemText(49, _translate("Exchange", "林吉特"))
        self.from_cur.setItemText(50, _translate("Exchange", "立陶宛立特"))
        self.from_cur.setItemText(51, _translate("Exchange", "卢布"))
        self.from_cur.setItemText(52, _translate("Exchange", "罗马尼亚新列伊"))
        self.from_cur.setItemText(53, _translate("Exchange", "毛里求斯卢比"))
        self.from_cur.setItemText(54, _translate("Exchange", "蒙古图格里特"))
        self.from_cur.setItemText(55, _translate("Exchange", "孟加拉塔卡"))
        self.from_cur.setItemText(56, _translate("Exchange", "缅甸缅元"))
        self.from_cur.setItemText(57, _translate("Exchange", "秘鲁新索尔"))
        self.from_cur.setItemText(58, _translate("Exchange", "摩洛哥迪拉姆"))
        self.from_cur.setItemText(59, _translate("Exchange", "墨西哥元"))
        self.from_cur.setItemText(60, _translate("Exchange", "南非兰特"))
        self.from_cur.setItemText(61, _translate("Exchange", "挪威克朗"))
        self.from_cur.setItemText(62, _translate("Exchange", "葡萄牙埃斯库多"))
        self.from_cur.setItemText(63, _translate("Exchange", "瑞典克朗"))
        self.from_cur.setItemText(64, _translate("Exchange", "瑞士法郎"))
        self.from_cur.setItemText(65, _translate("Exchange", "沙特里亚尔"))
        self.from_cur.setItemText(66, _translate("Exchange", "斯里兰卡卢比"))
        self.from_cur.setItemText(67, _translate("Exchange", "索马里先令"))
        self.from_cur.setItemText(68, _translate("Exchange", "泰铢"))
        self.from_cur.setItemText(69, _translate("Exchange", "坦桑尼亚先令"))
        self.from_cur.setItemText(70, _translate("Exchange", "新土耳其里拉"))
        self.from_cur.setItemText(71, _translate("Exchange", "突尼斯第纳尔"))
        self.from_cur.setItemText(72, _translate("Exchange", "危地马拉格查尔"))
        self.from_cur.setItemText(73, _translate("Exchange", "委内瑞拉玻利瓦尔"))
        self.from_cur.setItemText(74, _translate("Exchange", "乌拉圭新比索"))
        self.from_cur.setItemText(75, _translate("Exchange", "西班牙比塞塔"))
        self.from_cur.setItemText(76, _translate("Exchange", "希腊德拉克马"))
        self.from_cur.setItemText(77, _translate("Exchange", "新加坡元"))
        self.from_cur.setItemText(78, _translate("Exchange", "新台币"))
        self.from_cur.setItemText(79, _translate("Exchange", "新西兰元"))
        self.from_cur.setItemText(80, _translate("Exchange", "匈牙利福林"))
        self.from_cur.setItemText(81, _translate("Exchange", "牙买加元"))
        self.from_cur.setItemText(82, _translate("Exchange", "义大利里拉"))
        self.from_cur.setItemText(83, _translate("Exchange", "印度卢比"))
        self.from_cur.setItemText(84, _translate("Exchange", "印尼盾"))
        self.from_cur.setItemText(85, _translate("Exchange", "以色列谢克尔"))
        self.from_cur.setItemText(86, _translate("Exchange", "约旦第纳尔"))
        self.from_cur.setItemText(87, _translate("Exchange", "越南盾"))
        self.from_cur.setItemText(88, _translate("Exchange", "智利比索"))
        self.from_cur.setItemText(89, _translate("Exchange", "白俄罗斯卢布"))
        self.to_cur.setItemText(0, _translate("Exchange", "货币名称"))
        self.to_cur.setItemText(1, _translate("Exchange", "人民币"))
        self.to_cur.setItemText(2, _translate("Exchange", "美元"))
        self.to_cur.setItemText(3, _translate("Exchange", "日元"))
        self.to_cur.setItemText(4, _translate("Exchange", "欧元"))
        self.to_cur.setItemText(5, _translate("Exchange", "英镑"))
        self.to_cur.setItemText(6, _translate("Exchange", "韩元"))
        self.to_cur.setItemText(7, _translate("Exchange", "港币"))
        self.to_cur.setItemText(8, _translate("Exchange", "澳大利亚元"))
        self.to_cur.setItemText(9, _translate("Exchange", "加拿大元"))
        self.to_cur.setItemText(10, _translate("Exchange", "阿尔及利亚第纳尔"))
        self.to_cur.setItemText(11, _translate("Exchange", "阿根廷比索"))
        self.to_cur.setItemText(12, _translate("Exchange", "爱尔兰镑"))
        self.to_cur.setItemText(13, _translate("Exchange", "埃及镑"))
        self.to_cur.setItemText(14, _translate("Exchange", "阿联酋迪拉姆"))
        self.to_cur.setItemText(15, _translate("Exchange", "阿曼里亚尔"))
        self.to_cur.setItemText(16, _translate("Exchange", "奥地利先令"))
        self.to_cur.setItemText(17, _translate("Exchange", "澳门元"))
        self.to_cur.setItemText(18, _translate("Exchange", "百慕大元"))
        self.to_cur.setItemText(19, _translate("Exchange", "巴基斯坦卢比"))
        self.to_cur.setItemText(20, _translate("Exchange", "巴拉圭瓜拉尼"))
        self.to_cur.setItemText(21, _translate("Exchange", "巴林第纳尔"))
        self.to_cur.setItemText(22, _translate("Exchange", "巴拿马巴尔博亚"))
        self.to_cur.setItemText(23, _translate("Exchange", "保加利亚列弗"))
        self.to_cur.setItemText(24, _translate("Exchange", "巴西雷亚尔"))
        self.to_cur.setItemText(25, _translate("Exchange", "比利时法郎"))
        self.to_cur.setItemText(26, _translate("Exchange", "冰岛克朗"))
        self.to_cur.setItemText(27, _translate("Exchange", "博茨瓦纳普拉"))
        self.to_cur.setItemText(28, _translate("Exchange", "波兰兹罗提"))
        self.to_cur.setItemText(29, _translate("Exchange", "玻利维亚诺"))
        self.to_cur.setItemText(30, _translate("Exchange", "丹麦克朗"))
        self.to_cur.setItemText(31, _translate("Exchange", "德国马克"))
        self.to_cur.setItemText(32, _translate("Exchange", "法国法郎"))
        self.to_cur.setItemText(33, _translate("Exchange", "菲律宾比索"))
        self.to_cur.setItemText(34, _translate("Exchange", "芬兰马克"))
        self.to_cur.setItemText(35, _translate("Exchange", "哥伦比亚比索"))
        self.to_cur.setItemText(36, _translate("Exchange", "古巴比索"))
        self.to_cur.setItemText(37, _translate("Exchange", "哈萨克坚戈"))
        self.to_cur.setItemText(38, _translate("Exchange", "荷兰盾"))
        self.to_cur.setItemText(39, _translate("Exchange", "加纳塞地"))
        self.to_cur.setItemText(40, _translate("Exchange", "捷克克朗"))
        self.to_cur.setItemText(41, _translate("Exchange", "津巴布韦元"))
        self.to_cur.setItemText(42, _translate("Exchange", "卡塔尔里亚尔"))
        self.to_cur.setItemText(43, _translate("Exchange", "克罗地亚库纳"))
        self.to_cur.setItemText(44, _translate("Exchange", "肯尼亚先令"))
        self.to_cur.setItemText(45, _translate("Exchange", "科威特第纳尔"))
        self.to_cur.setItemText(46, _translate("Exchange", "老挝基普"))
        self.to_cur.setItemText(47, _translate("Exchange", "拉脱维亚拉图"))
        self.to_cur.setItemText(48, _translate("Exchange", "黎巴嫩镑"))
        self.to_cur.setItemText(49, _translate("Exchange", "林吉特"))
        self.to_cur.setItemText(50, _translate("Exchange", "立陶宛立特"))
        self.to_cur.setItemText(51, _translate("Exchange", "卢布"))
        self.to_cur.setItemText(52, _translate("Exchange", "罗马尼亚新列伊"))
        self.to_cur.setItemText(53, _translate("Exchange", "毛里求斯卢比"))
        self.to_cur.setItemText(54, _translate("Exchange", "蒙古图格里特"))
        self.to_cur.setItemText(55, _translate("Exchange", "孟加拉塔卡"))
        self.to_cur.setItemText(56, _translate("Exchange", "缅甸缅元"))
        self.to_cur.setItemText(57, _translate("Exchange", "秘鲁新索尔"))
        self.to_cur.setItemText(58, _translate("Exchange", "摩洛哥迪拉姆"))
        self.to_cur.setItemText(59, _translate("Exchange", "墨西哥元"))
        self.to_cur.setItemText(60, _translate("Exchange", "南非兰特"))
        self.to_cur.setItemText(61, _translate("Exchange", "挪威克朗"))
        self.to_cur.setItemText(62, _translate("Exchange", "葡萄牙埃斯库多"))
        self.to_cur.setItemText(63, _translate("Exchange", "瑞典克朗"))
        self.to_cur.setItemText(64, _translate("Exchange", "瑞士法郎"))
        self.to_cur.setItemText(65, _translate("Exchange", "沙特里亚尔"))
        self.to_cur.setItemText(66, _translate("Exchange", "斯里兰卡卢比"))
        self.to_cur.setItemText(67, _translate("Exchange", "索马里先令"))
        self.to_cur.setItemText(68, _translate("Exchange", "泰铢"))
        self.to_cur.setItemText(69, _translate("Exchange", "坦桑尼亚先令"))
        self.to_cur.setItemText(70, _translate("Exchange", "新土耳其里拉"))
        self.to_cur.setItemText(71, _translate("Exchange", "突尼斯第纳尔"))
        self.to_cur.setItemText(72, _translate("Exchange", "危地马拉格查尔"))
        self.to_cur.setItemText(73, _translate("Exchange", "委内瑞拉玻利瓦尔"))
        self.to_cur.setItemText(74, _translate("Exchange", "乌拉圭新比索"))
        self.to_cur.setItemText(75, _translate("Exchange", "西班牙比塞塔"))
        self.to_cur.setItemText(76, _translate("Exchange", "希腊德拉克马"))
        self.to_cur.setItemText(77, _translate("Exchange", "新加坡元"))
        self.to_cur.setItemText(78, _translate("Exchange", "新台币"))
        self.to_cur.setItemText(79, _translate("Exchange", "新西兰元"))
        self.to_cur.setItemText(80, _translate("Exchange", "匈牙利福林"))
        self.to_cur.setItemText(81, _translate("Exchange", "牙买加元"))
        self.to_cur.setItemText(82, _translate("Exchange", "义大利里拉"))
        self.to_cur.setItemText(83, _translate("Exchange", "印度卢比"))
        self.to_cur.setItemText(84, _translate("Exchange", "印尼盾"))
        self.to_cur.setItemText(85, _translate("Exchange", "以色列谢克尔"))
        self.to_cur.setItemText(86, _translate("Exchange", "约旦第纳尔"))
        self.to_cur.setItemText(87, _translate("Exchange", "越南盾"))
        self.to_cur.setItemText(88, _translate("Exchange", "智利比索"))
        self.to_cur.setItemText(89, _translate("Exchange", "白俄罗斯卢布"))
        self.label_4.setText(_translate("Exchange", "实时汇率转换 Exchange"))
        self.exchange_inquiry.setText(_translate("Exchange", "查      询"))
        self.timelabel.setText(_translate("Exchange", "TextLabel"))
        self.label.setText(_translate("Exchange", "当前系统时间："))
import icon_rc
